project: /Volumes/richter/projects/0069_0001
global: 
  num_procs: 4
# slurm:
#   partition: amarsden
#   python-path: ~/miniconda3/envs/estimator/bin/python
tasks:
  BloodVesselTuning:
    name: tmp_debug_test
    debug: True
    zerod_config_file: /Volumes/richter/projects/0069_0001/ROMSimulations/0069_0001/solver_0d.in
    threed_solution_file: /Volumes/richter/72_centerline_results_martin/0069_0001.vtp
    centerline_padding: False
    overwrite: True
  # WindkesselTuning:
  #   name: tmp_windkessel
  #   zerod_config_file: /Volumes/richter/projects/0069_0001/ROMSimulations/0069_0001/solver_0d.in
  #   theta_obs: [11.31430378, 9.56612492, 12.13497399, 11.89435741]
  #   y_obs: [7.96939000e+04, 1.28615495e+05, 1.17452432e+00, 5.73790727e+00, 5.16607267e-01, 6.57691899e-01]


  # MultiFidelityTuning:
  #   name: null
  #   num_iter: 3
  #   theta_obs: [11.31430378, 9.56612492, 12.13497399, 11.89435741]
  #   y_obs: [7.96939000e+04, 1.28615495e+05, 1.17452432e+00, 5.73790727e+00, 5.16607267e-01, 6.57691899e-01]
  #   smc_num_particles: 10000
  #   smc_num_rejuvenation_steps: 2
  #   smc_resampling_threshold: 0.5
  #   smc_noise_factor: 0.05
  #   num_cardiac_cycles_3d: 2
  #   svpre_executable: /home/users/pfaller/work/repos/svSolver_fork/build2/svSolver-build/bin/svpre
  #   svsolver_executable: /home/users/pfaller/work/repos/svSolver_fork/BuildWithMake/Bin/svsolver-openmpi.exe
  #   svpost_executable: /home/users/pfaller/work/repos/svSolver_fork/build2/svSolver-build/bin/svpost
  #   slicer_executable: /home/users/richter7/sanddorn-toolbox/slicer/Release/slicer
  #   MapThreeDResultOnCenterline: 
  #     num_procs: 12
